spring:
  datasource:
   driver-class-name: org.postgresql.Driver
   url: ${DB_URL}
   username: ${DB_USERNAME}
   password: ${DB_PASSWORD}

  jpa:
   hibernate:
     ddl-auto: none
     dialect: org.hibernate.dialect.PostgreSQLDialect
   properties:
     hibernate:
       default_batch_fetch_size: 100
       format_sql: true

  server:
    port: 8080
